[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"pallets/template",
	"pallets/sora2-trustless-bridge/beefy-light-client",
	"pallets/sora2-trustless-bridge/common",
	"runtime",
]
